### ISSUE TITLE
Last Name Comma First Name Format is not supported

### ISSUE THREAD

**Issue by jing928** [Ironholds/humaniformat#6]
_Last Name Comma First Name_ format like __SAMUELS, MITCHELL J__ is a pretty common format but it seems that the package doesn't support it.

Is there any plan on adding this feature?

**Comment by Ironholds** [comment]
firstname lastname is the supported format because the alternative is an endless series of parsing steps that can never actually ID anything, or a probabilistic approach similar to libpostal's address parsing. However, because of this the package contains name reformatters that reshape names in other, common formats to meet the parser's expectations. So if you know that names will be formatted lastname comma firstname:

```
library(humaniformat)
reformatted_name <- format_reverse("SAMUELS, MITCHELL J ")
parse_names(reformatted_name)

#  salutation first_name middle_name last_name suffix          full_name
#1       <NA>   MITCHELL           J   SAMUELS   <NA> MITCHELL J SAMUELS
> 
```
